services:
  postgres:
    image: postgres:16
    container_name: webelec-postgres
    restart: always
    environment:
      POSTGRES_DB: webelec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - webelec-net

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: webelec-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@webelec.be
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - webelec-net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  webelec-net:
